### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'permute'

### ISSUE THREAD

**Issue by TriBall3** [thomaschabal/transporter-nets-torch#1]
Hi，I met a bug when I train : `python ravens_torch/train.py --task=block-insertion --agent=transporter --n_demos=10`
Bug is bellow:

> pybullet build time: Mar 26 2022 03:00:15
> Loading trainset from /home/fty98/lab/fty/transporter-nets-torch/data/block-insertion-train
> Loading testset  from /home/fty98/lab/fty/transporter-nets-torch/data/block-insertion-test
> Writing logs at /home/fty98/lab/fty/transporter-nets-torch/data/logs/transporter/block-insertion/20220401-112549/train
> Running Attention model  on GPU
> Running Transport models on GPU
> /home/fty98/.conda/envs/ravens_torch/lib/python3.7/site-packages/torch/nn/functional.py:3063: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
>   "See the documentation of nn.Upsample for details.".format(mode))
> Traceback (most recent call last):
>   File "ravens_torch/train.py", line 63, in <module>
>     app.run(main)
>   File "/home/fty98/.conda/envs/ravens/lib/python3.7/site-packages/absl/app.py", line 312, in run
>     _run_main(main, args)
>   File "/home/fty98/.conda/envs/ravens/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
>     sys.exit(main(argv))
>   File "ravens_torch/train.py", line 56, in main
>     agent.train(train_dataset, writer)
>   File "/home/fty98/lab/fty/transporter-nets-torch/ravens_torch/agents/transporter.py", line 105, in train
>     loss1 = self.transport.train(img, p0, p1, p1_theta)
>   File "/home/fty98/lab/fty/transporter-nets-torch/ravens_torch/models/transport.py", line 178, in train
>     loss = self.train_block(in_img, p, q, theta)
>   File "/home/fty98/lab/fty/transporter-nets-torch/ravens_torch/models/transport.py", line 139, in train_block
>     output = self.forward(in_img, p, softmax=False)
>   File "/home/fty98/lab/fty/transporter-nets-torch/ravens_torch/models/transport.py", line 106, in forward
>     input_data = Rearrange('h w c -> 1 h w c')(input_data)
>   File "/home/fty98/.conda/envs/ravens_torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/fty98/.conda/envs/ravens_torch/lib/python3.7/site-packages/einops/layers/torch.py", line 14, in forward
>     return apply_for_scriptable_torch(self._recipe, input, reduction_type='rearrange')
>   File "/home/fty98/.conda/envs/ravens_torch/lib/python3.7/site-packages/einops/_torch_specific.py", line 81, in apply_for_scriptable_torch
>     tensor = backend.transpose(tensor, axes_reordering)
>   File "/home/fty98/.conda/envs/ravens_torch/lib/python3.7/site-packages/einops/_torch_specific.py", line 42, in transpose
>     return x.permute(axes)
> AttributeError: 'numpy.ndarray' object has no attribute 'permute'

Can you help me to solve this one ?

**Comment by onishu** [comment]
I had the same problem.
After reviewing the code, I found the following part to be the problem.

https://github.com/thomaschabal/transporter-nets-torch/blob/be5adaee9eb225be8ec894f8b40426e7fa1042c6/ravens_torch/models/transport.py#L106

I thought the problem might be due to a change in the version of "einops",  so I changed the version to "0.3.2" and the error was resolved.

**Comment by thomaschabal** [comment]
Hi,

Thank you for pointing out this error and the solution to fix it. The code has been updated accordingly.

Best,
Thomas
